# Default values for ctc-5gucp-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 172.18.1.157/public
  image: qa124_ema80_mod_server
  pullPolicy: Always
  tag: v1

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 10

service:
  type: NodePort
  port: service1_port
  httpnodePort: service1_httpnodePort
  debugenable: false
  debugnodePort: 32016

environment: {
  ENV: UAT,
  cluster: uat,
  MAX_MEMORY: 1024m,
  WEB_TYPE: web,
}

imagePullSecrets:
  enable: true
  secretsname: harbor

hostnames: {
  172.18.1.126: [apollo.metaservice.dahancloud.com]
}
  
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: 5gucp-web-server.dahanema.com
      paths: ['/']
  tls: []

resources: 
  limits:
    memory: 1536Mi
  requests:
    memory: 1024Mi

persistence:
  enabled: true
  storageClass: dynamic-cephfs
  accessMode: ReadWriteOnce
  size: 1024Mi
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
    # targetMemoryUtili:zationPercentage: 80
