apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctc-5gucp-license.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      {{- if .Values.service.httpnodePort }}
      nodePort: {{ .Values.service.httpnodePort }}
      {{- end }}
    {{- if .Values.service2 }}
    - port: {{ .Values.service2.port }}
      targetPort: {{ .Values.service2.port }}
      protocol: TCP
      name: http2
      {{- if .Values.service2.httpnodePort }}
      nodePort: {{ .Values.service2.httpnodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.debugenable }}
    - port: 11098
      targetPort: 11098
      protocol: TCP
      name: debug
      {{- if .Values.service.debugnodePort }}
      nodePort: {{ .Values.service.debugnodePort }}
      {{- end }}    
    {{- end }}
  selector:
    name: {{ template "ctc-5gucp-license.fullname" . }}
